--------------------------------------
--Create the Stud_Marks Table
--CREATE TABLE Stud_Marks (
    --name VARCHAR2(100),
    --total_marks NUMBER
--);
--Insert sample data into the Stud_Marks table

--Create the Result Table:
--CREATE TABLE Result (
    --Roll NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    --Name VARCHAR2(100),
    --Class VARCHAR2(50)
--);
--Create the Stored Procedure proc_Grade
--------------------------------------

CREATE OR REPLACE PROCEDURE proc_Grade AS CURSOR cur_marks IS SELECT name, total_marks FROM Stud_Marks;

v_class VARCHAR2(50);

BEGIN
    FOR student IN cur_marks LOOP
        -- Categorize based on total marks
        IF student.total_marks BETWEEN 990 AND 1500 THEN
            v_class := 'Distinction';
        ELSIF student.total_marks BETWEEN 900 AND 989 THEN
            v_class := 'First Class';
        ELSIF student.total_marks BETWEEN 825 AND 899 THEN
            v_class := 'Higher Second Class';
        ELSE
            v_class := 'No Class';
        END IF;

        -- Insert result into the Result table
        INSERT INTO Result (Name, Class)
        VALUES (student.name, v_class);
    END LOOP;
    COMMIT;
END;
/

-----------------------------------
--Execute the Procedure
--To execute the proc_Grade procedure and populate the Result table:
--BEGIN
    --proc_Grade;
--END;
--/
--After running the procedure, check the Result table to see the categorization of students
----------------------------------
